dist: trusty
language: csharp
mono: none
services:
  - postgresql
before_script:
  - psql -c "alter user postgres password '1234'" -U postgres
sudo: required
dotnet: 3.0.100
solution: DynamicQueryBuilder.sln
script:
- scripts/test.sh
